### ISSUE TITLE
gojs如何从后台获取数据

### ISSUE THREAD

**Issue by torfuzx** [Lanfei/GoJS#1]
gojs如何从后台通过get异步获取数据，然后进行渲染。

**Comment by Lanfei** [comment]
抱歉最近特别忙，几乎没怎么上 GitHub。

如果想把 JSON 数据当做模块来管理的话，可以使用 [go-json 插件](http://lanfei.github.io/GoJS/docs/index.html#go-json)。

不过一般都是通过 AJAX 模块配合模板引擎来实现。

**Comment by torfuzx** [comment]
谢谢
